name: Node CI

on:
  push:
    branches:
      - work

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install --save mime-db
          npm install -g hexo-cli
          npm install lunr
          npm install
          hexo g

        env:
          CI: true

      - name: Build and Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    
